services:
  backend:
    image: jayanthroyal/social-backend:latest
    container_name: social-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: jayanthroyal/social-frontend:latest
    container_name: social-frontend
    ports:
      - "3000:80"
    restart: always
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: social-redis
    restart: always