services:
  backend:
    image: jayanthroyal/social-backend:latest
    container_name: social-backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: jayanthroyal/social-frontend:latest
    container_name: social-frontend
    ports:
      - "3000:80"
    restart: always

  redis:
    image: redis:7-alpine
    container_name: social-redis
    restart: always