# Use official Node image
FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Add logs
RUN mkdir -p logs

# Copy app source
COPY . .

# Expose backend port
EXPOSE 5000

# Start app
CMD ["npm", "start"]